export {default as Header} from '../sections/header/header'
export {default as Hero} from '../sections/hero/hero'
export {default as Footer} from '../sections/footer/footer'
export {default as Mostpopular} from '../sections/mostpopular/mostpopular'
export {default as GamingLibrary} from '../sections/GamingLibrary/GamingLibrary'